"""
BBOX-ADAPTER: MLM-based Adapter (Ablation Baseline)

Implements the Masked Language Modeling (MLM) loss adapter used as an ablation
baseline in §4.5 (Table 5). This is the comparison method for the NCE loss ablation.

MLM Training (§4.5):
  - Generate text chunks from ground-truth data
  - Randomly mask words in the chunks
  - Train the adapter using the masked word as supervision signal

MLM Inference (§4.5):
  - Mask a random word in each sequence generated by beam search
  - Score the sequence based on the probability of the masked word

Results (Table 5):
  - StrategyQA 0.1B: 61.52% (vs NCE: 71.62%)
  - StrategyQA 0.3B: 60.41% (vs NCE: 71.18%)
  - GSM8K 0.1B: 70.56% (vs NCE: 72.06%)
  - GSM8K 0.3B: 70.81% (vs NCE: 73.86%)
"""

import torch
import torch.nn as nn
import random
from typing import List, Optional
from transformers import (
    AutoModelForMaskedLM,
    AutoTokenizer,
)


def build_mlm_adapter(
    critic_model: str,  # e.g., "microsoft/deberta-v3-base"
) -> nn.Module:
    """
    Build adapter for MLM-based training (ablation baseline).
    Uses AutoModelForMaskedLM instead of classification head.

    Args:
        critic_model: HuggingFace model with masked LM capability

    Returns:
        model: AutoModelForMaskedLM
    """
    model = AutoModelForMaskedLM.from_pretrained(
        critic_model,
        trust_remote_code=True,
    )
    return model


def mask_random_word(
    tokens: List[int],
    mask_token_id: int,
    special_token_ids: List[int],
) -> tuple:
    """
    Randomly mask one non-special token in the token sequence.
    Used in both MLM training (from ground-truth) and inference (from beam candidates).

    Args:
        tokens: List of token IDs
        mask_token_id: ID of [MASK] token in vocabulary
        special_token_ids: IDs of [CLS], [SEP], [PAD] to exclude from masking

    Returns:
        (masked_tokens, masked_position, original_token_id)
    """
    maskable_positions = [
        i for i, tok in enumerate(tokens)
        if tok not in special_token_ids
    ]
    if not maskable_positions:
        return tokens, -1, -1

    mask_pos = random.choice(maskable_positions)
    original_token = tokens[mask_pos]
    masked_tokens = tokens.copy()
    masked_tokens[mask_pos] = mask_token_id
    return masked_tokens, mask_pos, original_token


def compute_mlm_loss(
    model: nn.Module,
    input_ids: torch.Tensor,        # shape: (B, seq_len); contains [MASK] tokens
    attention_mask: torch.Tensor,   # shape: (B, seq_len)
    masked_labels: torch.Tensor,    # shape: (B, seq_len); -100 for non-masked positions
) -> torch.Tensor:
    """
    Compute MLM training loss: cross-entropy on masked token prediction.
    Used in the ablation study (§4.5).

    MLM Training procedure (§4.5):
    1. Generate text chunks from ground-truth data
    2. Randomly mask words
    3. Train adapter to predict masked words

    Args:
        model: MLM adapter (AutoModelForMaskedLM)
        input_ids: Token IDs with one random token per sequence replaced by [MASK]
        attention_mask: Attention mask
        masked_labels: Ground-truth token IDs; -100 for non-masked tokens (ignored in loss)

    Returns:
        loss: MLM cross-entropy loss
    """
    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask,
        labels=masked_labels,  # HuggingFace computes CE loss automatically
    )
    return outputs.loss


def score_with_mlm(
    model: nn.Module,
    tokenizer: AutoTokenizer,
    text: str,
    device: torch.device,
    add_special_tokens: bool = True,
) -> float:
    """
    Score a text sequence using MLM inference.
    MLM Inference procedure (§4.5):
    1. Mask a random word in the sequence
    2. Score the sequence based on the masked word's predicted probability (log-prob)

    Args:
        model: Trained MLM adapter
        tokenizer: Tokenizer matching the adapter
        text: Full (question + partial answer) text string
        device: torch.device

    Returns:
        score: Log-probability of the masked token (higher = better)
    """
    encoding = tokenizer(
        text,
        return_tensors="pt",
        add_special_tokens=add_special_tokens,
        truncation=True,
    )
    input_ids = encoding["input_ids"].squeeze(0).tolist()

    special_ids = [
        tokenizer.cls_token_id,
        tokenizer.sep_token_id,
        tokenizer.pad_token_id,
    ]
    masked_tokens, mask_pos, original_token = mask_random_word(
        input_ids, tokenizer.mask_token_id, special_ids
    )
    if mask_pos == -1:
        return 0.0

    masked_input = torch.tensor([masked_tokens]).to(device)
    attn_mask = encoding["attention_mask"].to(device)

    model.eval()
    with torch.no_grad():
        outputs = model(input_ids=masked_input, attention_mask=attn_mask)
        logits = outputs.logits  # shape: (1, seq_len, vocab_size)

    log_probs = torch.log_softmax(logits[0, mask_pos, :], dim=-1)
    return log_probs[original_token].item()
